lang: &lang
  name: "lang"
  label: "Lang"
  default: "en"
  widget: "select"
  options: &langOptions
    - { label: "English", value: "en" }
    - { label: "Chinese", value: "zh" }

backend:
  name: "github"
  repo: "connet-tw/connet"
  branch: "master"

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  ##### SETTINGS
  - name: "settings-en"
    label: "Settings EN"
    editor:
      preview: false
    files:
      - label: "General Settings"
        name: "settings"
        file: "src/data/settings/settings.en.yml"
        fields:
          - { label: "Title", name: "title" }
          - { label: "Phone", name: "email" }
          - { label: "Email", name: "phone" }
  ##### PAGES
  - name: "pages-en"
    label: "Pages EN"
    editor:
      preview: false
    files:
      - label: "Index Page"
        name: "index"
        file: "src/data/content/index.en.yml"
        fields:
          - { label: "Title", name: "title" }
          - { label: "Subtitle", name: "subtitle", required: false }
          - { label: "Image", name: "image", widget: "image" }
          - name: "welcomeSection"
            label: "Welcome Section"
            widget: "object"
            fields:
              - { label: "Body", name: "markdown", widget: "markdown" }
          - name: "servicesSection"
            label: "Services Section"
            widget: "object"
            fields:
              - { label: "Body", name: "markdown", widget: "markdown" }

      - label: "About Page"
        name: "about"
        file: "src/data/content/about.en.yml"
        fields:
          - { label: "Title", name: "title" }
          - { label: "Subtitle", name: "subtitle", required: false }
          - { label: "Intro", name: "markdown", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - name: "referencesSection"
            label: "References"
            widget: "object"
            fields:
              - { label: "Title", name: "title" }
              - { label: "Subtitle", name: "subtitle", required: false }

      - label: "Contact Page"
        name: "contact"
        file: "src/data/content/contact.en.yml"
        fields:
          - { label: "Title", name: "title" }
          - { label: "Subtitle", name: "subtitle", required: false }
          - { label: "Intro", name: "markdown", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - name: "contacts"
            label: "Contacts"
            widget: "list"
            fields:
              - { label: "Title", name: "title" }
              - { label: "Phone", name: "phone" }
              - { label: "Email", name: "email" }
              - { label: "Street", name: "street" }
              - { label: "District", name: "district" }
              - { label: "City", name: "city" }
              - { label: "Post Code", name: "postCode" }
              - { label: "Country", name: "country" }

      - label: "Services Page"
        name: "services"
        file: "src/data/content/services.en.yml"
        fields:
          - { label: "Title", name: "title" }
          - { label: "Subtitle", name: "subtitle", required: false }
          - { label: "Intro", name: "markdown", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }

  ##### REFERENCES
  - name: "references en"
    label: "References EN"
    folder: "src/data/references"
    identifier_field: "name"
    create: true
    fields:
      - *lang
      - { name: "name", label: "Name" }
      - { name: "date", label: "Date" }
      - { name: "title", label: "Title" }
      - { name: "customer", label: "Customer", required: false }
      - { name: "location", label: "Location", required: false }
      - { name: "body", label: "Content", widget: "markdown", required: false }

  - name: "services-en"
    label: "Services EN"
    folder: "src/data/services"
    filter: { field: "lang", value: "en" }
    create: true
    fields:
      - *lang
      - { name: "title", label: "Title" }
      - { name: "subtitle", label: "Subtitle" }
      - {
          name: "image",
          label: "Header Image",
          widget: "image",
          allow_multiple: false,
        }
      - { name: "order", label: "Order", widget: "number" }
      - { name: "body", label: "Content", widget: "markdown" }
